#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets username")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # get screen_name's tweets
    tweets = helpers.get_user_timeline(sys.argv[1], 50)
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        text = str(score) + " " + tweet
        if score > 0.0:
            print(colored(text, "green"))
        elif score < 0.0:
            print(colored(text, "red"))
        else:
            print(colored(text, "yellow"))

if __name__ == "__main__":
    main()
